# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://augustoparis.github.io/

title : Augusto Paris

author:
  name: Augusto Paris
  role: Desenvolvedor Web por profissão. Jogador de poker por diversão!
  email: support@ankanbiswas.in
  github: augustoparis
  twitter: augustoparis
  facebook: augustodacunhaparis
  googleplus: +AnkanBiswasWorkspace
  bio: Olá, seja bem-vindo! Eu criei esse blog com um objetivo principal: compartilhar os conhecimentos que venho estudando e aplicando no meu dia a dia e que me fizeram dar um salto na minha produtividade, energia e qualidade de vida, me dando cada vez mais gás pra fazer o que eu amo, jogar poker.
  bio2: /assets/media/poker.png
  iconpoker: /assets/media/espadas.png
  avatar: /assets/media/augustoparis.jpg
  uno-dbyll: https://raw.githubusercontent.com/talk2ankan/uno-dbyll/gh-pages/uno-dbyll.png
